#!/bin/bash
cd $(dirname $0)/../..

export WORKON_HOME=$(pwd)/.venv

source $(which virtualenvwrapper.sh)
if [ $? != 0 ]
then
  echo "Missing prerequisite virtualenvwrapper, bailing out"
  exit 1
fi

if (! test -d "$WORKON_HOME/.home_automation")
then
  echo "Creating virtual env for .home_automation"
  mkvirtualenv ".home_automation"
fi

echo "Working on virtualenv home_automation"
source "$WORKON_HOME/.home_automation/bin/activate"

echo "Installing python package requirements.."
pip install -r requirements.txt
